plugins {
    id 'org.relativitymc.neo-loom' version "1.17+"
    id 'maven-publish'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

loom {
    accessWidenerPath = file("src/main/resources/toms_mobs.accesswidener")
}

repositories {
    maven { url 'https://maven.tomalbrc.de' }
    maven { url 'https://maven.nucleoid.xyz' }
    maven { url 'https://maven.blamejared.com' }
    maven { url 'https://dl.cloudsmith.io/public/tslat/sbl/maven/' }
    mavenLocal()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    //implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    //implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    forgeUserdev "net.neoforged:neoforge:${project.neo_version}:userdev"

    implementation include("eu.pb4:polymer-bundled-neo:${project.polymer_version}")

    implementation include("de.tomalbrc:blockbench-import-library-neo:${project.bil_version}")

    implementation include("net.tslat:smartbrainlib-neoforge-26.1.2:${project.sbl_version}") {
        transitive = false
    }
}

processResources {
    inputs.property "version", rootProject.version
    inputs.property "minecraft_version", rootProject.minecraft_version
    inputs.property "loader_version", rootProject.loader_version
    filteringCharset "UTF-8"

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": rootProject.version,
                "minecraft_version": rootProject.minecraft_version,
                "loader_version": rootProject.loader_version
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}


tasks.withType(JavaCompile).configureEach {
    it.options.release.set(25)
}

java {
    withSourcesJar()
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {

    }
}
