# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=3.2.0
maven_group=de.tomalbrc
archives_base_name=toms_mobs

# Dependencies
fabric_version=0.160.5+26.3
polymer_version=0.18.0+26.3-rc-1
bil_version=2.2.0+26.3-rc-3
sbl_version=2.0.0

neo_version=26.2.0.1-beta

curseforge_project_id=1118755