# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.2

# Mod Properties
mod_version=3.0.5
maven_group=de.tomalbrc
archives_base_name=toms_mobs

# Dependencies
fabric_version=0.152.1+26.2
polymer_version=0.17.0+26.2-rc-2
bil_version=2.0.7+26.2
sbl_version=1.17-alpha-2

neo_version=26.2.0.1-beta

curseforge_project_id=1118755